{
    "singleReply": {
        "appDetailsV2Reply": {
            "extraContentPageBodyInfo": {
                "pageBody": {
                    "rows": [
                        {
                            "simpleAppList": {
                                "apps": [
                                    {
                                        "info": {
                                            "packageName": "com.juventus.app.android",
                                            "rate": 4.2,
                                        },
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.homemade.ffm2",
                                            "name": "(FPL) Fantasy Football Manager for Premier League",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.homemade.ffm2_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.8,
                                            "authorName": "Homemade Apps",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":1,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.football.fitness",
                                            "name": "بدنسازی فوتبال با وزنه",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.football.fitness_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 10,
                                            "rate": 3.2,
                                            "authorName": "پدیده تشان",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 10000,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "۱,۰۰۰ تومان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":2,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.excellenceutility.kitserver",
                                            "name": "DLS kits- Dream League Kits 2021",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.excellenceutility.kitserver_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4,
                                            "authorName": "KITKIT",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":3,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.sportandtravel.biketracker",
                                            "name": "Bike Tracker",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.sportandtravel.biketracker_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.7,
                                            "authorName": "Sport \u0026 Travel",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":4,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "babrian.bodybuilding.stroid",
                                            "name": "دوپینگ در ورزش های قدرتی",
                                            "image": "https://cafe.bzrcdn.net/1/icons/babrian.bodybuilding.stroid_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 7,
                                            "rate": 3,
                                            "authorName": "badanfitir",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 50000,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "۵,۰۰۰ تومان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":5,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.tgbsco.medal",
                                            "name": "مدال | نتایج زنده و پیش بینی فوتبال",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.tgbsco.medal_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 16,
                                            "rate": 4.1,
                                            "authorName": "گروه بادبادک",
                                            "hasInAppPurchase": true,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":6,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.sports.schedules.basketball.nba",
                                            "name": "Basketball NBA Live Scores, Stats, \u0026 Schedules",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.sports.schedules.basketball.nba_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 5,
                                            "authorName": "Scores App",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":7,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.mcentric.mcclient.FCBWorld",
                                            "name": "FC Barcelona Official App",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.mcentric.mcclient.FCBWorld_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 16,
                                            "rate": 4.4,
                                            "authorName": "F.C. Barcelona",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":8,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "se.footballaddicts.livescore",
                                            "name": "Forza Football - Live soccer scores",
                                            "image": "https://cafe.bzrcdn.net/1/icons/se.footballaddicts.livescore_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 8,
                                            "rate": 4.7,
                                            "authorName": "Forza Football",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":9,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                ],
                                "isAd": false,
                                "identifier": {
                                    "path": "list~app~automatic~APP_ACCESSORIES_RELATED~421562"
                                },
                                "rowUpdateInfo": {"ttl": "-1", "actions": []},
                            }
                        },
                        {
                            "simpleAppList": {
                                "apps": [
                                    {
                                        "info": {
                                            "packageName": "com.totalfreeapps.secure.incoming.call.locker.pincode",
                                            "name": "Incoming Call Pin Locker",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.totalfreeapps.secure.incoming.call.locker.pincode_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 2.6,
                                            "authorName": "Total Free Apps",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "personalization",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":0,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.hasbro.riskbigscreen",
                                            "name": "RISK: Global Domination",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.hasbro.riskbigscreen_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.3,
                                            "authorName": "SMG Studio",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "strategy",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":1,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.letterboxd.letterboxd",
                                            "name": "Letterboxd",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.letterboxd.letterboxd_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 5,
                                            "authorName": "Letterboxd Limited",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "social",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":2,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.allemailproviderapps2019.newemailappsall",
                                            "name": "Email All-in-one: Free Online Mail, Secure Mailbox",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.allemailproviderapps2019.newemailappsall_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 3.8,
                                            "authorName": "social app 43",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "tools",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":3,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "free.videotube.playtube.videoder.video.downloader.v2",
                                            "name": "Video Tube - Video Downloader - Play Tube",
                                            "image": "https://cafe.bzrcdn.net/1/icons/free.videotube.playtube.videoder.video.downloader.v2_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 2.3,
                                            "authorName": "Video Play Tube Apps",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "photography",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":4,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.music.hero.free.mp3.cutter.ringtone.maker",
                                            "name": "Music cutter ringtone maker - MP3 cutter editor",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.music.hero.free.mp3.cutter.ringtone.maker_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 29,
                                            "rate": 4.3,
                                            "authorName": "Music Hero - Best Free music \u0026 audio app developer",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "personalization",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":5,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.systweak.systemoptimizer",
                                            "name": "Cleaner For Android :Phone Booster \u0026 RAM Optimizer",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.systweak.systemoptimizer_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.4,
                                            "authorName": "SYSTWEAK SOFTWARE",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "tools",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":6,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.weaponoid.miband4",
                                            "name": "Mi Band 4 WatchFaces",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.weaponoid.miband4_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 22,
                                            "rate": 5,
                                            "authorName": "Akash Chaudhary",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "tools",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":7,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.mcentric.mcclient.MyMadrid",
                                            "name": "Real Madrid App",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.mcentric.mcclient.MyMadrid_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 14,
                                            "rate": 4.3,
                                            "authorName": "Real Madrid C.F.",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":8,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.kokteyl.goal",
                                            "name": "Goal Live Scores",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.kokteyl.goal_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 8,
                                            "rate": 4.4,
                                            "authorName": "Goal.com",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":9,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                ],
                            }
                        },
                        {
                            "simpleAppList": {
                                "title": "برنامه‌های مشابه",
                                "expandInfo": {
                                    "show": false,
                                    "vitrinExpandInfo": {
                                        "path": "list~app~automatic~APP_ACCESSORIES_SIMILAR~421562"
                                    },
                                },
                                "description": "",
                                "referrer": {
                                    "type": 1,
                                    "extraJson": '{"service":"shelf","number":3,"title":"similar-apps","source":"normal","targetedRow":"related-page-below-reviews","is_shuffled":false,"group":"A-NotShuffled5"}',
                                },
                                "apps": [
                                    {
                                        "info": {
                                            "packageName": "yong.tools.life.weather",
                                            "name": "Weather: Live Weather Forecast",
                                            "image": "https://cafe.bzrcdn.net/1/icons/yong.tools.life.weather_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 21,
                                            "rate": 3.8,
                                            "authorName": "GentleMan Dev Studio",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "weather",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":0,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.microtech.magicwallpaper",
                                            "name": "3D Parallax Live Wallpaper - 4K Backgrounds",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.microtech.magicwallpaper_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 21,
                                            "rate": 2.9,
                                            "authorName": "3d background",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "personalization",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":1,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.komspek.battleme",
                                            "name": "Rap Fame – رپر شو!",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.komspek.battleme_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.3,
                                            "authorName": "Rap Tech Studios",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "music-audio",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":2,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.viewer.comicscreen",
                                            "name": "ComicScreen - PDF, ComicReader",
                                            "image": "https://s.cafebazaar.ir/images/icons/com.viewer.comicscreen-9d92f8ef-275b-4399-9d4e-6c6a07925978_512x512.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.9,
                                            "authorName": "InstSoft",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "books-reference",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":3,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.englishlearning.englishgrammar",
                                            "name": "Egrammar - learn english grammar",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.englishlearning.englishgrammar_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 5,
                                            "authorName": "Lenavin .s.t.d",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "education",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":4,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.domobile.aut.cblack",
                                            "name": "AppLock Theme Black",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.domobile.aut.cblack_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 3.1,
                                            "authorName": "AppLock@DoMobile",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "tools",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":5,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.hardgrnd.lineup11",
                                            "name": "Lineup11- Football Line-up",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.hardgrnd.lineup11_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.1,
                                            "authorName": "footplr",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":6,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.football.favorite",
                                            "name": "Football Squad Builder",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.football.favorite_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4,
                                            "authorName": "clstudio.info",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":7,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "tiraxtur.f.c",
                                            "name": "تیراختور اف سی",
                                            "image": "https://cafe.bzrcdn.net/1/icons/tiraxtur.f.c_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 22,
                                            "rate": 5,
                                            "authorName": "تیراختور اف سی",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":8,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                    {
                                        "info": {
                                            "packageName": "com.bluelinden.coachboard",
                                            "name": "Coach Tactic Board: Soccer",
                                            "image": "https://cafe.bzrcdn.net/1/icons/com.bluelinden.coachboard_128x128.png",
                                            "versionCode": 0,
                                            "minimumSdkVersion": 19,
                                            "rate": 4.3,
                                            "authorName": "BLUELINDEN",
                                            "hasInAppPurchase": false,
                                            "isEnabled": true,
                                            "incompatible": false,
                                            "category": "sports",
                                            "shortDescription": "",
                                            "installCountVerbose": "",
                                            "installCountVerboseLabel": "",
                                            "installCountVerboseDescription": "",
                                            "screenshots": [],
                                            "paymentInfo": {
                                                "price": 0,
                                                "priceBeforeDiscount": -1,
                                                "priceString": "رایگان",
                                                "priceBeforeDiscountString": "",
                                            },
                                            "verboseReviewCount": "",
                                            "verboseSize": "",
                                            "verboseSizeLabel": "",
                                            "videoTrailer": null,
                                            "showScreenshotsType": 0,
                                            "thirdPartyPayment": null,
                                        },
                                        "referrer": {
                                            "type": 2,
                                            "extraJson": '{"service":"vitrin","index":9,"referrer_identifier":""}',
                                        },
                                        "isAd": false,
                                        "adData": null,
                                    },
                                ],
                                "isAd": false,
                                "identifier": {
                                    "path": "list~app~automatic~APP_ACCESSORIES_SIMILAR~421562"
                                },
                                "rowUpdateInfo": {"ttl": "-1", "actions": []},
                            }
                        },
                    ],
                },
            },
        }
    },
}
